### ISSUE TITLE
Error on Nested ItemAttachmentable serialization

### ISSUE THREAD

**Issue by dadams39** [microsoft/kiota-serialization-json-go#61]
Messageable and Eventable can possess one of the 3 different types of attachments. Item Attachmetables are recursive. In the process of trying to send an object with a Nested ItemAttachmentable object, the following error is returned:
```
panic: interface conversion: interface is nil, not serialization.Parsable [recovered]
	panic: interface conversion: interface is nil, not serialization.Parsable

goroutine 8 [running]:
testing.tRunner.func1.2({0x10765e680, 0x14000cd4900})
	/opt/homebrew/Cellar/go/1.19.2/libexec/src/testing/testing.go:1396 +0x1c8
testing.tRunner.func1()
	/opt/homebrew/Cellar/go/1.19.2/libexec/src/testing/testing.go:1399 +0x378
panic({0x10765e680, 0x14000cd4900})
	/opt/homebrew/Cellar/go/1.19.2/libexec/src/runtime/panic.go:884 +0x204
github.com/microsoftgraph/msgraph-sdk-go/models.(*Message).Serialize(0x140005bac00, {0x1083a22e8, 0x14000cac930})
	/Users/dadams39/go/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.53.0/models/message.go:579 +0x1100
github.com/microsoft/kiota-serialization-json-go.(*JsonSerializationWriter).WriteObjectValue(0x14000cac930, {0x106793293?, 0x4}, {0x108387e10, 0x140005bac00}, {0x0, 0x0, 0x0?})
	/Users/dadams39/go/pkg/mod/github.com/microsoft/kiota-serialization-json-go@v0.7.2/json_serialization_writer.go:257 +0x240
github.com/microsoftgraph/msgraph-sdk-go/models.(*ItemAttachment).Serialize(0x14000394410, {0x1083a22e8, 0x14000cac930})
	/Users/dadams39/go/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.53.0/models/item_attachment.go:52 +0x80
github.com/microsoft/kiota-serialization-json-go.(*JsonSerializationWriter).WriteObjectValue(0x14000cac930, {0x0?, 0x0}, {0x108386b78, 0x14000394410}, {0x0, 0x0, 0x107f335a0?})
	/Users/dadams39/go/pkg/mod/github.com/microsoft/kiota-serialization-json-go@v0.7.2/json_serialization_writer.go:257 +0x240
github.com/microsoft/kiota-abstractions-go.(*RequestInformation).SetContentFromParsable(0x14000194090?, {0x1083955e0, 0x140002367b0}, {0x10839a418, 0x14000063950}, {0x1067a7195, 0x10}, {0x108386b78?, 0x14000394410?})
	/Users/dadams39/go/pkg/mod/github.com/microsoft/kiota-abstractions-go@v0.16.0/request_information.go:215 +0x23c
github.com/microsoftgraph/msgraph-sdk-go/users.(*ItemMailFoldersItemMessagesItemAttachmentsRequestBuilder).ToPostRequestInformation(0x1400024f1a0, {0x1083955e0, 0x140002367b0}, {0x13262a050?, 0x14000394410}, 0x0)
	/Users/dadams39/go/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.53.0/users/item_mail_folders_item_messages_item_attachments_request_builder.go:146 +0x1e8
github.com/microsoftgraph/msgraph-sdk-go/users.(*ItemMailFoldersItemMessagesItemAttachmentsRequestBuilder).Post(0x1400024f1a0, {0x1083955e0, 0x140002367b0}, {0x13262a050?, 0x14000394410?}, 0x10492a680?)
	/Users/dadams39/go/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.53.0/users/item_mail_folders_item_messages_item_attachments_request_builder.go:106 +0x30
```

It was unclear whether or not this error belonged in the abstraction repository or in this directory. While the error is returned from the Graph API, the error can be returned when trying to serialize the object alone.

**Comment by dadams39** [comment]
Sanitized test data
```json
{
	"@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users('<userID>')/messages(attachments())/$entity",
	"@odata.etag": "W/\"<NotApplied>\"",
	"id": "AAMkAGQ1NzViZTdSAAA=",
	"createdDateTime": "2023-02-02T21:38:27Z",
	"lastModifiedDateTime": "2023-02-02T22:42:49Z",
	"changeKey": "CQAAABYAAAB8wYc0thTTTYl3RpEYIUq+AADFK782",
	"categories": [],
	"receivedDateTime": "2023-02-02T21:38:27Z",
	"sentDateTime": "2023-02-02T21:38:24Z",
	"hasAttachments": true,
	"internetMessageId": "<SJ0PR17MB562287BE29A86751D6E77FE5C3D69@SJ0PR17MB5622.namprd17.prod.outlook.com>",
	"subject": "%[1]v",
	"bodyPreview": "Dustin,\r\n\r\nI'm here to see if we are still able to discover our object.",
	"importance": "normal",
	"parentFolderId": "AQMkAGQ1NzViZTdhLTEwMTMtNGJjNi05YWI2LTg4ADVkZWQwNmNlMTgALgAAAw_9XBStqZdPuOVIalVTz7sBAHzBhzS2FNNNiXdGkRghSr4AAAIBDAAAAA==",
	"conversationId": "AAQkAGQ1NzViZTdhLTEwMTMtNGJjNi05YWI2LTg4NWRlZDA2Y2UxOAAQAB13OyMdkNJJqEaIrGi3Yjc=",
	"conversationIndex": "AQHZN06dHXc7Ix2Q0kmoRoisaLdiNw==",
	"isDeliveryReceiptRequested": false,
	"isReadReceiptRequested": false,
	"isRead": false,
	"isDraft": false,
	"webLink": "https://outlook.office365.com/owa/?ItemID=AAMkAGQ1NzTruncated",
	"inferenceClassification": "focused",
	"body": {
	  "contentType": "html",
	  "content": "<html><head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"><style type=\"text/css\" style=\"display:none\">\r\n<!--\r\np\r\n\t{margin-top:0;\r\n\tmargin-bottom:0}\r\n-->\r\n</style></head><body dir=\"ltr\"><div class=\"elementToProof\" style=\"font-family:Calibri,Arial,Helvetica,sans-serif; font-size:12pt; color:rgb(0,0,0); background-color:rgb(255,255,255)\">Dustin,</div><div class=\"elementToProof\" style=\"font-family:Calibri,Arial,Helvetica,sans-serif; font-size:12pt; color:rgb(0,0,0); background-color:rgb(255,255,255)\"><br></div><div class=\"elementToProof\" style=\"font-family:Calibri,Arial,Helvetica,sans-serif; font-size:12pt; color:rgb(0,0,0); background-color:rgb(255,255,255)\">I'm here to see if we are still able to discover our object.&nbsp;</div></body></html>"
	},
	"sender": {
	  "emailAddress": {
		"name": "%[2]s",
		"address": "%[3]s"
	  }
	},
	"from": {
	  "emailAddress": {
		"name": "%[2]s",
		"address": "%[4]s"
	  }
	},
	"toRecipients": [
	  {
		"emailAddress": {
		  "name": "%[2]s",
		  "address": "%[5]s"
		}
	  }
	],
	"ccRecipients": [],
	"bccRecipients": [],
	"replyTo": [],
	"flag": {
	  "flagStatus": "notFlagged"
	},
	"attachments": [
	  {
		"@odata.type": "#microsoft.graph.itemAttachment",
		"id": "AAMkAGQ1NzViZ1ZccRCjKKyF7VZ3dA=",
		"lastModifiedDateTime": "2023-02-02T21:38:27Z",
		"name": "Mail Item Attachment",
		"contentType": null,
		"size": 5362,
		"isInline": false,
		"item@odata.associationLink": "https://graph.microsoft.com/v1.0/users('f435c656-f8b2-4d71-93c3-6e092f52a167')/messages('')/$ref",
		"item@odata.navigationLink": "https://graph.microsoft.com/v1.0/users('f435c656-f8b2-4d71-93c3-6e092f52a167')/messages('')",
		"item": {
		  "@odata.type": "#microsoft.graph.message",
		  "id": "",
		  "createdDateTime": "2023-02-02T21:38:27Z",
		  "lastModifiedDateTime": "2023-02-02T21:38:27Z",
		  "receivedDateTime": "2023-02-01T13:48:47Z",
		  "sentDateTime": "2023-02-01T13:48:46Z",
		  "hasAttachments": true,
		  "internetMessageId": "<SJ0PR17MB56220B4F6A443386A11D5154C3D19@SJ0PR17MB5622.namprd17.prod.outlook.com>",
		  "subject": "Mail Item Attachment",
		  "bodyPreview": "Lookingtodothis",
		  "importance": "normal",
		  "conversationId": "AAQkAGQ1NzViZTdhLTEwMTMtNGJjNi05YWI2LTg4NWRlZDA2Y2UxOAAQAMNK0NU7Kx5GhAaHdzhfSRU=",
		  "conversationIndex": "AQHZN02pw0rQ1TsrHkaEBod3OF9JFQ==",
		  "isDeliveryReceiptRequested": false,
		  "isReadReceiptRequested": false,
		  "isRead": true,
		  "isDraft": false,
		  "webLink": "https://outlook.office365.com/owa/?AttachmentItemID=AAMkAGQ1NzViZTdhLTEwMTM",
		  "body": {
			"contentType": "html",
			"content": "<html><head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"><metahttp-equiv=\"Content-Type\"content=\"text html;charset=\"utf-8&quot;\"><styletype=\"text css?style=\"display:none\"><!--\r\np\r\n\t{margin-top:0;\r\n\tmargin-bottom:0}\r\n--><bodydir=\"ltr\"><divclass=\"elementToProof\"style=\"font-family:Calibri,Arial,Helvetica,sans-serif;font-size:12pt;color:rgb(0,0,0);background-color:rgb(255,255,255)\"></head><body>Lookingtodothis&nbsp; <div></div></body></html>"
		  },
		  "sender": {
			"emailAddress": {
			  "name": "A Stranger",
			  "address": "foobar@my.onmicrosoft.com"
			}
		  },
		  "from": {
			"emailAddress": {
			  "name": "A Stranger",
			  "address": "foobar@my.onmicrosoft.com"
			}
		  },
		  "toRecipients": [
			{
			  "emailAddress": {
				"name": "Direct Report",
				"address":  "notAvailable@my.onmicrosoft.com"
			  }
			}
		  ],
		  "flag": {
			"flagStatus": "notFlagged"
		  },
		  "attachments": [
			{
			  "@odata.type": "#microsoft.graph.itemAttachment",
			  "id": "AAMkAGQ1NzViZTdhLTEwMTMtNGJjNi05YWI2LTg4NWRlZDA2Y2UxOABGAAAAAAAPvVwUramXT7jlSGpVU8_7BwB8wYc0thTTTYl3RpEYIUq_AAAAAAEMAAB8wYc0thTTTYl3RpEYIUq_AADFfThSAAACEgAQAIyAgT1ZccRCjKKyF7VZ3dASABAAuYCb3N2YZ02RpJrZPzCBFQ==",
			  "lastModifiedDateTime": "2023-02-02T21:38:27Z",
			  "name": "Holidayevent",
			  "contentType": null,
			  "size": 2331,
			  "isInline": false,
			  "item@odata.associationLink": "https://graph.microsoft.com/v1.0/users('f435c656-f8b2-4d71-93c3-6e092f52a167')/events('')/$ref",
			  "item@odata.navigationLink": "https://graph.microsoft.com/v1.0/users('f435c656-f8b2-4d71-93c3-6e092f52a167')/events('')",
			  "item": {
				"@odata.type": "#microsoft.graph.event",
				"id": "",
				"createdDateTime": "2023-02-02T21:38:27Z",
				"lastModifiedDateTime": "2023-02-02T21:38:27Z",
				"originalStartTimeZone": "tzone://Microsoft/Utc",
				"originalEndTimeZone": "tzone://Microsoft/Utc",
				"reminderMinutesBeforeStart": 0,
				"isReminderOn": false,
				"hasAttachments": false,
				"subject": "Discuss Gifts for Children",
				"isAllDay": false,
				"isCancelled": false,
				"isOrganizer": true,
				"responseRequested": true,
				"type": "singleInstance",
				"isOnlineMeeting": false,
				"isDraft": true,
				"body": {
				  "contentType": "html",
				  "content": "<html><head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"><metahttp-equiv=\"Content-Type\"content=\"text html;charset=\"utf-8&quot;\"></head><body>Let'slookforfunding! </body></html>"
				},
				"start": {
				  "dateTime": "2016-12-02T18:00:00.0000000Z",
				  "timeZone": "UTC"
				},
				"end": {
				  "dateTime": "2016-12-02T19:00:00.0000000Z",
				  "timeZone": "UTC"
				},
				"organizer": {
				  "emailAddress": {
					"name": "Event Manager",
					"address": "philonis@my.onmicrosoft.com"
				  }
				}
			  }
			}
		  ]
		}
	  }
	]
}
```

Some of these fields are removed, but unable to show the current bytes due to the serialization failure.

**Comment by dadams39** [comment]
Certainly, the failure happens during the writeObjectValue call
The `testBytes` is the value above:
```go
        wtr := kioser.NewJsonSerializationWriter()
	message, err := support.CreateMessageFromBytes(test.bytes)
	err = wtr.WriteObjectValue("", message)
```

**Comment by dadams39** [comment]
The specific cause of the failure seems to be the `itemAttachment` field `attachments` being `non-nil` upon serialization.

**Comment by rkodev** [comment]
Hi @dadams39 , Are you able to confirm that this is still the case with `v0.8.2` of this library?

**Comment by rkodev** [comment]
Issue has been fixed as of v0.8.2

**Comment by neha-Gupta1** [comment]
Can still see the same issue in - `kiota-serialization-text-go v1.0.0`
The code panics with - `panic: interface conversion: interface is nil, not serialization.Parsable`

**Comment by neha-Gupta1** [comment]
Filed a new issue https://github.com/microsoft/kiota-serialization-json-go/issues/91 for tracking the error.
