### ISSUE TITLE
Error on Nested ItemAttachmentable serialization

### ISSUE THREAD

**Issue by neha-Gupta1** [microsoft/kiota-serialization-json-go#91]
[Error on Nested ItemAttachmentable serialization #61](https://github.com/microsoft/kiota-serialization-json-go/issues/61)  is still present in version - `kiota-serialization-json-go v1.0.1`
Issue - Messageable and Eventable can possess one of the 3 different types of attachments. Item Attachmetables are recursive. In the process of trying to send an object with a Nested ItemAttachmentable object, the following error is returned:

`panic: interface conversion: interface is nil, not serialization.Parsable [recovered]
	panic: interface conversion: interface is nil, not serialization.Parsable`

Scenario and the output are exactly same as mentioned in above [issue](https://github.com/microsoft/kiota-serialization-json-go/issues/61).

**Comment by baywet** [comment]
Thanks for reaching out.
What type (go data type) is this attachment of attachment when you instantiate the object?

**Comment by baywet** [comment]
Can you provide a small reproduction code please?

**Comment by neha-Gupta1** [comment]
You will need a nested attachment something of type- 
```{
	"@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users('<userID>')/messages(attachments())/$entity",
	"@odata.etag": "W/\"<NotApplied>\"",
	"id": "AAMkAGQ1NzViZTdSAAA=",
	"createdDateTime": "2023-02-02T21:38:27Z",
	"lastModifiedDateTime": "2023-02-02T22:42:49Z",
	"changeKey": "CQAAABYAAAB8wYc0thTTTYl3RpEYIUq+AADFK782",
	"categories": [],
	"receivedDateTime": "2023-02-02T21:38:27Z",
	"sentDateTime": "2023-02-02T21:38:24Z",
	"hasAttachments": true,
	"internetMessageId": "<SJ0PR17MB562287BE29A86751D6E77FE5C3D69@SJ0PR17MB5622.namprd17.prod.outlook.com>",
	"subject": "%[1]v",
	"bodyPreview": "Dustin,\r\n\r\nI'm here to see if we are still able to discover our object.",
	"importance": "normal",
	"parentFolderId": "AQMkAGQ1NzViZTdhLTEwMTMtNGJjNi05YWI2LTg4ADVkZWQwNmNlMTgALgAAAw_9XBStqZdPuOVIalVTz7sBAHzBhzS2FNNNiXdGkRghSr4AAAIBDAAAAA==",
	"conversationId": "AAQkAGQ1NzViZTdhLTEwMTMtNGJjNi05YWI2LTg4NWRlZDA2Y2UxOAAQAB13OyMdkNJJqEaIrGi3Yjc=",
	"conversationIndex": "AQHZN06dHXc7Ix2Q0kmoRoisaLdiNw==",
	"isDeliveryReceiptRequested": false,
	"isReadReceiptRequested": false,
	"isRead": false,
	"isDraft": false,
	"webLink": "https://outlook.office365.com/owa/?ItemID=AAMkAGQ1NzTruncated",
	"inferenceClassification": "focused",
	"body": {
	  "contentType": "html",
	  "content": "<html><head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"><style type=\"text/css\" style=\"display:none\">\r\n<!--\r\np\r\n\t{margin-top:0;\r\n\tmargin-bottom:0}\r\n-->\r\n</style></head><body dir=\"ltr\"><div class=\"elementToProof\" style=\"font-family:Calibri,Arial,Helvetica,sans-serif; font-size:12pt; color:rgb(0,0,0); background-color:rgb(255,255,255)\">Dustin,</div><div class=\"elementToProof\" style=\"font-family:Calibri,Arial,Helvetica,sans-serif; font-size:12pt; color:rgb(0,0,0); background-color:rgb(255,255,255)\"><br></div><div class=\"elementToProof\" style=\"font-family:Calibri,Arial,Helvetica,sans-serif; font-size:12pt; color:rgb(0,0,0); background-color:rgb(255,255,255)\">I'm here to see if we are still able to discover our object.&nbsp;</div></body></html>"
	},
	"sender": {
	  "emailAddress": {
		"name": "%[2]s",
		"address": "%[3]s"
	  }
	},
	"from": {
	  "emailAddress": {
		"name": "%[2]s",
		"address": "%[4]s"
	  }
	},
	"toRecipients": [
	  {
		"emailAddress": {
		  "name": "%[2]s",
		  "address": "%[5]s"
		}
	  }
	],
	"ccRecipients": [],
	"bccRecipients": [],
	"replyTo": [],
	"flag": {
	  "flagStatus": "notFlagged"
	},
	"attachments": [
	  {
		"@odata.type": "#microsoft.graph.itemAttachment",
		"id": "AAMkAGQ1NzViZ1ZccRCjKKyF7VZ3dA=",
		"lastModifiedDateTime": "2023-02-02T21:38:27Z",
		"name": "Mail Item Attachment",
		"contentType": null,
		"size": 5362,
		"isInline": false,
		"item@odata.associationLink": "https://graph.microsoft.com/v1.0/users('f435c656-f8b2-4d71-93c3-6e092f52a167')/messages('')/$ref",
		"item@odata.navigationLink": "https://graph.microsoft.com/v1.0/users('f435c656-f8b2-4d71-93c3-6e092f52a167')/messages('')",
		"item": {
		  "@odata.type": "#microsoft.graph.message",
		  "id": "",
		  "createdDateTime": "2023-02-02T21:38:27Z",
		  "lastModifiedDateTime": "2023-02-02T21:38:27Z",
		  "receivedDateTime": "2023-02-01T13:48:47Z",
		  "sentDateTime": "2023-02-01T13:48:46Z",
		  "hasAttachments": true,
		  "internetMessageId": "<SJ0PR17MB56220B4F6A443386A11D5154C3D19@SJ0PR17MB5622.namprd17.prod.outlook.com>",
		  "subject": "Mail Item Attachment",
		  "bodyPreview": "Lookingtodothis",
		  "importance": "normal",
		  "conversationId": "AAQkAGQ1NzViZTdhLTEwMTMtNGJjNi05YWI2LTg4NWRlZDA2Y2UxOAAQAMNK0NU7Kx5GhAaHdzhfSRU=",
		  "conversationIndex": "AQHZN02pw0rQ1TsrHkaEBod3OF9JFQ==",
		  "isDeliveryReceiptRequested": false,
		  "isReadReceiptRequested": false,
		  "isRead": true,
		  "isDraft": false,
		  "webLink": "https://outlook.office365.com/owa/?AttachmentItemID=AAMkAGQ1NzViZTdhLTEwMTM",
		  "body": {
			"contentType": "html",
			"content": "<html><head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"><metahttp-equiv=\"Content-Type\"content=\"text html;charset=\"utf-8&quot;\"><styletype=\"text css?style=\"display:none\"><!--\r\np\r\n\t{margin-top:0;\r\n\tmargin-bottom:0}\r\n--><bodydir=\"ltr\"><divclass=\"elementToProof\"style=\"font-family:Calibri,Arial,Helvetica,sans-serif;font-size:12pt;color:rgb(0,0,0);background-color:rgb(255,255,255)\"></head><body>Lookingtodothis&nbsp; <div></div></body></html>"
		  },
		  "sender": {
			"emailAddress": {
			  "name": "A Stranger",
			  "address": "foobar@my.onmicrosoft.com"
			}
		  },
		  "from": {
			"emailAddress": {
			  "name": "A Stranger",
			  "address": "foobar@my.onmicrosoft.com"
			}
		  },
		  "toRecipients": [
			{
			  "emailAddress": {
				"name": "Direct Report",
				"address":  "notAvailable@my.onmicrosoft.com"
			  }
			}
		  ],
		  "flag": {
			"flagStatus": "notFlagged"
		  },
		  "attachments": [
			{
			  "@odata.type": "#microsoft.graph.itemAttachment",
			  "id": "AAMkAGQ1NzViZTdhLTEwMTMtNGJjNi05YWI2LTg4NWRlZDA2Y2UxOABGAAAAAAAPvVwUramXT7jlSGpVU8_7BwB8wYc0thTTTYl3RpEYIUq_AAAAAAEMAAB8wYc0thTTTYl3RpEYIUq_AADFfThSAAACEgAQAIyAgT1ZccRCjKKyF7VZ3dASABAAuYCb3N2YZ02RpJrZPzCBFQ==",
			  "lastModifiedDateTime": "2023-02-02T21:38:27Z",
			  "name": "Holidayevent",
			  "contentType": null,
			  "size": 2331,
			  "isInline": false,
			  "item@odata.associationLink": "https://graph.microsoft.com/v1.0/users('f435c656-f8b2-4d71-93c3-6e092f52a167')/events('')/$ref",
			  "item@odata.navigationLink": "https://graph.microsoft.com/v1.0/users('f435c656-f8b2-4d71-93c3-6e092f52a167')/events('')",
			  "item": {
				"@odata.type": "#microsoft.graph.event",
				"id": "",
				"createdDateTime": "2023-02-02T21:38:27Z",
				"lastModifiedDateTime": "2023-02-02T21:38:27Z",
				"originalStartTimeZone": "tzone://Microsoft/Utc",
				"originalEndTimeZone": "tzone://Microsoft/Utc",
				"reminderMinutesBeforeStart": 0,
				"isReminderOn": false,
				"hasAttachments": false,
				"subject": "Discuss Gifts for Children",
				"isAllDay": false,
				"isCancelled": false,
				"isOrganizer": true,
				"responseRequested": true,
				"type": "singleInstance",
				"isOnlineMeeting": false,
				"isDraft": true,
				"body": {
				  "contentType": "html",
				  "content": "<html><head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"><metahttp-equiv=\"Content-Type\"content=\"text html;charset=\"utf-8&quot;\"></head><body>Let'slookforfunding! </body></html>"
				},
				"start": {
				  "dateTime": "2016-12-02T18:00:00.0000000Z",
				  "timeZone": "UTC"
				},
				"end": {
				  "dateTime": "2016-12-02T19:00:00.0000000Z",
				  "timeZone": "UTC"
				},
				"organizer": {
				  "emailAddress": {
					"name": "Event Manager",
					"address": "philonis@my.onmicrosoft.com"
				  }
				}
			  }
			}
		  ]
		}
	  }
	]
}```

And then try to Post the above message. For this Post through `Send Mail` and then Post attachments to it.
```
import kjson "github.com/microsoft/kiota-serialization-json-go"

func serializeData(){
sw := kjson.NewJsonSerializationWriter()

err := sw.WriteObjectValue("", data)
if err != nil {
	return "", clues.Wrap(err, "writing serializing info")
}

// seems like the error starts here. 
content, err := sw.GetSerializedContent()
if err != nil {
	return "", clues.Wrap(err, "getting serializing info")
}

// *msgraphsdkgo.GraphServiceClient client
_, err := Client().
		Users().
		ByUserId(<userID>).
		MailFolders().
		ByMailFolderId(<containerID>).
		Messages().
		ByMessageId(<parentItemID>).
		Attachments().
		Post(ctx, content, nil)
	if err != nil {
		return graph.Wrap(ctx, err, "uploading small mail attachment")
	}
}
```

**Comment by rkodev** [comment]
Hi @neha-Gupta1, on the example snippet given I'm unable to determine the source of `data` variable. Could you clarify this?

**Comment by neha-Gupta1** [comment]
It is of type `serialization.Parsable` and its the `nested attachment` object I mentioned in above comment. Updating above comments for more clarification.

**Comment by rkodev** [comment]
Hi @neha-Gupta, I was able to identify the issue and we should have this issue fixed in the next scheduled release of the SDK.

**Comment by neha-Gupta1** [comment]
Thank you for the update @rkodev

**Comment by neha-Gupta1** [comment]
@rkodev the code still fails with the below similar error- 

```
testing.tRunner.func1()
        /home/nehagupta/sdk/go1.20.5/src/testing/testing.go:1529 +0x39f
panic({0x2ca5de0, 0xc0002bb800})
        /home/nehagupta/sdk/go1.20.5/src/runtime/panic.go:884 +0x213
github.com/microsoftgraph/msgraph-sdk-go/models.(*Message).Serialize(0xc000365f00, {0x3c70ea0, 0xc000798c80})
        /tmp/go/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v1.4.0/models/message.go:729 +0x114
github.com/microsoft/kiota-serialization-json-go.(*JsonSerializationWriter).WriteObjectValue(0xc000798c80, {0x372407b?, 0x4}, {0x3c50ba8, 0xc000365f00}, {0x0, 0x0, 0x0?})
        /tmp/go/pkg/mod/github.com/microsoft/kiota-serialization-json-go@v1.0.2/json_serialization_writer.go:273 +0x1da
github.com/microsoftgraph/msgraph-sdk-go/models.(*ItemAttachment).Serialize(0xc000ba46a0, {0x3c70ea0, 0xc000798c80})
        /tmp/go/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v1.4.0/models/item_attachment.go:57 +0x87
github.com/microsoft/kiota-serialization-json-go.(*JsonSerializationWriter).WriteObjectValue(0xc000798c80, {0x0?, 0x0}, {0x3c4f848, 0xc000ba46a0}, {0x0, 0x0, 0x90?})
        /tmp/go/pkg/mod/github.com/microsoft/kiota-serialization-json-go@v1.0.2/json_serialization_writer.go:273 +0x1da
github.com/microsoft/kiota-abstractions-go.(*RequestInformation).SetContentFromParsable(0xc000014620?, {0x3c5f780, 0xc0002bb350}, {0x3c64f10, 0xc0000c14f0}, {0x373942f, 0x10}, {0x3c4f848?, 0xc000ba46a0?})
        /tmp/go/pkg/mod/github.com/microsoft/kiota-abstractions-go@v1.0.0/request_information.go:215 +0x304
github.com/microsoftgraph/msgraph-sdk-go/users.(*ItemMailFoldersItemMessagesItemAttachmentsRequestBuilder).ToPostRequestInformation(0xc00017f6a0, {0x3c5f780, 0xc0002bb350}, {0x3c68f50?, 0xc000ba46a0}, 0x0)
        /tmp/go/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v1.4.0/users/item_mail_folders_item_messages_item_attachments_request_builder.go:146 +0x245
github.com/microsoftgraph/msgraph-sdk-go/users.(*ItemMailFoldersItemMessagesItemAttachmentsRequestBuilder).Post(0xc00017f6a0, {0x3c5f780, 0xc0002bb350}, {0x3c68f50?, 0xc000ba46a0?}, 0x0?)
        /tmp/go/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v1.4.0/users/item_mail_folders_item_messages_item_attachments_request_builder.go:106 +0x36
```

The data we are trying to POST is exactly same as mentioned above.

**Comment by rkodev** [comment]
@neha-Gupta1 This fix will be complete with release of version 1.8.0 this week.

**Comment by neha-Gupta1** [comment]
Okay. Got it. Thank you for informing.
